package de.infix.testBalloon.gradlePlugin

import buildConfig.BuildConfig.PROJECT_ABSTRACTIONS_ARTIFACT_ID
import buildConfig.BuildConfig.PROJECT_COMPILER_PLUGIN_ARTIFACT_ID
import buildConfig.BuildConfig.PROJECT_COMPILER_PLUGIN_ID
import buildConfig.BuildConfig.PROJECT_GROUP_ID
import buildConfig.BuildConfig.PROJECT_JUNIT_PLATFORM_LAUNCHER
import buildConfig.BuildConfig.PROJECT_VERSION
import org.gradle.api.Project
import org.gradle.api.provider.Provider
import org.gradle.api.tasks.testing.Test
import org.jetbrains.kotlin.gradle.dsl.KotlinBaseExtension
import org.jetbrains.kotlin.gradle.plugin.KotlinCompilation
import org.jetbrains.kotlin.gradle.plugin.KotlinCompilerPluginSupportPlugin
import org.jetbrains.kotlin.gradle.plugin.SubpluginArtifact
import org.jetbrains.kotlin.gradle.plugin.SubpluginOption
import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask
import kotlin.collections.iterator
import kotlin.io.path.Path
import kotlin.io.path.div
import kotlin.io.path.exists
import kotlin.io.path.writeText
import kotlin.reflect.KProperty

@Suppress("unused")
class GradlePlugin : KotlinCompilerPluginSupportPlugin {
    private class PluginProperties(val project: Project) {

        /** Name pattern for the subset of Kotlin compilation tasks which test compilation tasks. */
        val kotlinTestCompilationTaskRegex by regexProperty("""Test""")

        /** Name pattern for test root source sets which will receive generated entry point code. */
        val testRootSourceSetRegex by regexProperty(
            """^(test$|commonTest$|androidTest|androidInstrumentedTest)"""
        )

        /**
         * Name pattern for test compilations in which the compiler plugin will look up test suites and a test session.
         *
         * The Gradle plugin will only apply the compiler plugin for compilations matching this pattern.
         */
        val testCompilationRegex by regexProperty("""(^test)|Test""")

        /**
         * Name pattern for tasks processing source code from test source sets, like those from KSP.
         *
         * The Gradle plugin will make these tasks depend on the TestBalloon task generating the entry point source file.
         */
        val testSourceCodeProcessingTaskRegex by regexProperty("""^kspTestKotlin""")

        /**
         * Name pattern for test modules in which the compiler plugin will look up test suites and a test session.
         *
         * The Compiler plugin will disable itself for modules not matching this pattern.
         */
        val testModuleRegex by stringProperty("""(_test|Test)$""")

        @Suppress("SameParameterValue")
        private fun stringProperty(default: String) = Delegate(default) { it }
        private fun regexProperty(default: String) = Delegate(default) { Regex(it) }

        inner class Delegate<Result>(val default: String, val conversion: (String) -> Result) {
            operator fun getValue(thisRef: Any?, property: KProperty<*>): Result =
                conversion(project.findProperty("testBalloon.${property.name}")?.toString() ?: default)
        }
    }

    private lateinit var pluginProperties: PluginProperties

    override fun apply(target: Project): Unit = with(target) {
        pluginProperties = PluginProperties(this)

        extensions.create("testBalloon", GradleExtension::class.java)

        // WORKAROUND https://youtrack.jetbrains.com/issue/KT-53477 – KGP misses transitive compiler plugin dependencies
        configurations.named("kotlinNativeCompilerPluginClasspath") {
            dependencies.add(
                project.dependencies.create("$PROJECT_GROUP_ID:$PROJECT_ABSTRACTIONS_ARTIFACT_ID:$PROJECT_VERSION")
            )
        }

        val testRootSourceSetRegex = pluginProperties.testRootSourceSetRegex
        val generatedCommonTestDir = layout.buildDirectory.dir("generated/testBalloon/src/commonTest")

        extensions.configure<KotlinBaseExtension>("kotlin") {
            sourceSets.configureEach {
                if (testRootSourceSetRegex.containsMatchIn(name)) {
                    kotlin.srcDir(generatedCommonTestDir)
                }
            }
        }

        val generateTestBalloonInitializationTask = tasks.register("generateTestBalloonInitialization") {
            outputs.dir(generatedCommonTestDir)
            doLast {
                val directory = Path("${generatedCommonTestDir.get()}/kotlin")
                check(directory.exists() || directory.toFile().mkdirs()) { "Could not create directory '$directory'" }
                (directory / "EntryPointAnchor.kt").writeText(
                    """
                        package de.infix.testBalloon.framework.internal.entryPoint

                        // This file was generated by Gradle plugin id("$PROJECT_GROUP_ID") version "$PROJECT_VERSION".
                        // The compiler plugin will populate it with entry point code. 

                    """.trimIndent()
                )
            }
        }

        // Make Kotlin compilation tasks aware of the generated source's origin.
        val kotlinTestCompilationTaskRegex = pluginProperties.kotlinTestCompilationTaskRegex
        tasks.withType(KotlinCompilationTask::class.java) {
            if (kotlinTestCompilationTaskRegex.containsMatchIn(name)) {
                dependsOn(generateTestBalloonInitializationTask)
            }
        }

        // Make source code processing tasks (like KSP) aware of the generated source's origin.
        val testSourceCodeProcessingTaskRegex = pluginProperties.testSourceCodeProcessingTaskRegex
        tasks.configureEach {
            if (testSourceCodeProcessingTaskRegex.containsMatchIn(name)) {
                dependsOn(generateTestBalloonInitializationTask)
            }
        }

        tasks.withType(Test::class.java) {
            // https://docs.gradle.org/current/userguide/java_testing.html
            useJUnitPlatform()

            // Ask Gradle to skip scanning for test classes. We don't need it as our compiler plugin already
            // knows. Does this make a difference? I don't know.
            isScanForTestClasses = false

            // Pass TEST_* environment variables from the Gradle invocation to the test JVM.
            for ((name, value) in providers.environmentVariablesPrefixedBy("TEST_").get()) {
                environment(name, value)
            }

            // Pass TEST_* system properties as environment variables. NOTE: Doesn't help with K/Native.
            for ((name, value) in providers.systemPropertiesPrefixedBy("TEST_").get()) {
                environment(name, value)
            }
        }

        val testRuntimeOnlyConfigurations = setOf("testRuntimeOnly", "jvmTestRuntimeOnly")

        configurations.configureEach {
            if (name in testRuntimeOnlyConfigurations) {
                dependencies.add(project.dependencies.create(PROJECT_JUNIT_PLATFORM_LAUNCHER))
            }
        }
    }

    override fun isApplicable(kotlinCompilation: KotlinCompilation<*>): Boolean {
        val project = kotlinCompilation.target.project
        val extension = project.extensions.getByType(GradleExtension::class.java)
        return pluginProperties.testCompilationRegex.containsMatchIn(kotlinCompilation.name).also {
            if (extension.debugLevel > DebugLevel.NONE) {
                project.logger.warn(
                    "[DEBUG] $PLUGIN_DISPLAY_NAME is ${if (!it) "not " else ""}applicable" +
                        " for Kotlin compilation '${kotlinCompilation.name}'"
                )
            }
        }
    }

    override fun applyToCompilation(kotlinCompilation: KotlinCompilation<*>): Provider<List<SubpluginOption>> {
        val project = kotlinCompilation.target.project
        val extension = project.extensions.getByType(GradleExtension::class.java)

        return project.provider {
            listOf(
                SubpluginOption(key = "debugLevel", value = extension.debugLevel.toString()),
                SubpluginOption(key = "jvmStandalone", value = extension.jvmStandalone.toString()),
                SubpluginOption(key = "testModuleRegex", value = pluginProperties.testModuleRegex)
            )
        }
    }

    override fun getCompilerPluginId(): String = PROJECT_COMPILER_PLUGIN_ID

    override fun getPluginArtifact(): SubpluginArtifact = SubpluginArtifact(
        groupId = PROJECT_GROUP_ID,
        artifactId = PROJECT_COMPILER_PLUGIN_ARTIFACT_ID,
        version = PROJECT_VERSION
    )
}

private const val PLUGIN_DISPLAY_NAME = "Plugin $PROJECT_COMPILER_PLUGIN_ID"
