# suppress inspection "UnusedProperty" for whole file
kotlin.code.style=official
kotlin.native.ignoreDisabledTargets=true

# WORKAROUND https://youtrack.jetbrains.com/issue/KT-78504 - yarn NpmInstall tasks produce broken build cache entries
kotlin.js.yarn=false

kotlin.build.report.output=file
kotlin.build.report.enable=true
kotlin.build.report.verbose=true

# https://kotlinlang.org/docs/gradle-compilation-and-caches.html#the-kotlin-daemon-and-how-to-use-it-with-gradle
# Use compiler-specific options instead of inheriting them from Gradle. This also ensures that a single
# compiler daemon is used even if several Gradle daemons are in play.
kotlin.daemon.jvmargs=-Xmx1500m -Xms500m

# https://docs.gradle.org/current/userguide/build_cache.html
# The build cache must be disabled, otherwise tests would reuse cached results and not actually run as intended.
org.gradle.caching=false
# https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
# https://docs.gradle.org/current/userguide/performance.html#parallel_execution
org.gradle.parallel=false
# 'org.gradle.jvmargs' and 'org.gradle.daemon.idletimeout' are set per project via CLI parameters.

android.useAndroidX=true
