@file:OptIn(TestBalloonInternalApi::class)

package de.infix.testBalloon.compilerPlugin.layer.kotlin230

import CompilerPluginBaseTests
import com.tschuchort.compiletesting.SourceFile
import de.infix.testBalloon.framework.shared.internal.Constants
import de.infix.testBalloon.framework.shared.internal.TestBalloonInternalApi
import kotlin.test.Test

@Suppress("ClassName")
private class CompilerPluginTests_2_3_0 {
    private val jvmEntryPointClassSimpleName = Constants.JVM_ENTRY_POINT_CLASS_NAME.substringAfterLast('.')

    private val base = CompilerPluginBaseTests(
        externalEntryPointSourceFile = SourceFile.kotlin(
            "$jvmEntryPointClassSimpleName.kt",
            @Suppress(
                "RedundantSuppression",
                "RedundantVisibilityModifier",
                "RedundantExplicitType",
                "RedundantSuspendModifier"
            )
            """
                        package ${Constants.ENTRY_POINT_PACKAGE_NAME}
                        // In real-world use cases, this file is generated by the Gradle plugin.
                        // The compiler plugin will populate it with entry point code. 

                        internal class $jvmEntryPointClassSimpleName { // for JVM targets
                            companion object {
                                internal fun ${Constants.JVM_DISCOVERY_RESULT_METHOD_NAME}() {}
                            }
                        }
                        
                        public suspend fun main() {} // for JS and Wasm targets
                        
                        private val testFrameworkNativeEntryPoint: Unit = Unit
            """.trimIndent()
        )
    )

    @Test
    fun versioning() = base.versioning(adapterVersion = "2.3.0", compilerVersion = "2.3.0")

    @Test
    fun initialization() = base.initialization()

    @Test
    fun insistOnSingleTestSession() = base.insistOnSingleTestSession()

    @Test
    fun topLevelSuiteVisibility() = base.topLevelSuiteVisibility()

    @Test
    fun topLevelSuiteWithArgumentReordering() = base.topLevelSuiteWithArgumentReordering()

    @Test
    fun discoveryDebugLogging() = base.discoveryDebugLogging()

    @Test
    fun defectiveFrameworkLibraryDependency() = base.defectiveFrameworkLibraryDependency()
}
