@file:OptIn(TestBalloonInternalApi::class)

package buildLogic

import de.infix.testBalloon.framework.shared.internal.Constants
import de.infix.testBalloon.framework.shared.internal.TestBalloonInternalApi
import de.infix.testBalloon.gradlePlugin.shared.TestBalloonGradleExtension
import de.infix.testBalloon.gradlePlugin.shared.TestBalloonGradleProperties
import de.infix.testBalloon.gradlePlugin.shared.compilerPluginOptionValues
import de.infix.testBalloon.gradlePlugin.shared.configureWithTestBalloon
import org.gradle.api.Project
import org.gradle.api.artifacts.Dependency
import org.gradle.api.artifacts.UnknownConfigurationException
import org.jetbrains.kotlin.gradle.dsl.HasConfigurableKotlinCompilerOptions
import org.jetbrains.kotlin.gradle.plugin.NATIVE_COMPILER_PLUGIN_CLASSPATH_CONFIGURATION_NAME
import org.jetbrains.kotlin.gradle.plugin.PLUGIN_CLASSPATH_CONFIGURATION_NAME

/**
 * Adds the configuration normally supplied by the project's own Gradle plugin.
 *
 * This enables the project's compiler plugin without loading it from a repository.
 */
fun Project.addTestBalloonPluginFromProject(compilerPluginDependency: Dependency) {
    val testBalloonProperties = TestBalloonGradleProperties(this)

    // Add the compiler plugin as done by TestBalloonGradlePlugin.
    dependencies.add(PLUGIN_CLASSPATH_CONFIGURATION_NAME, compilerPluginDependency)
    try {
        dependencies.add(NATIVE_COMPILER_PLUGIN_CLASSPATH_CONFIGURATION_NAME, compilerPluginDependency)
    } catch (_: UnknownConfigurationException) {
        // The configuration "kotlinNativeCompilerPluginClasspath" is unavailable with AGP9's built-in Kotlin.
    }

    configureWithTestBalloon(
        testBalloonProperties = testBalloonProperties,
        pluginDisplayName = "Plugin ${Constants.COMPILER_PLUGIN_NAME}",
        junitPlatformLauncher = libraryFromCatalog("org.junit.platform.launcher")
    )

    // Configure compiler plugin options as done by KotlinCompilerPluginSupportPlugin.
    extensions.configure<HasConfigurableKotlinCompilerOptions<*>>("kotlin") {
        compilerOptions {
            freeCompilerArgs.addAll(
                provider {
                    // Lazily configuring the compiler options ensures that the extension is guaranteed to be present
                    // and the build script (including extension settings) has been completely evaluated.
                    val extension = extensions.getByType(TestBalloonGradleExtension::class.java)
                    compilerPluginOptionValues(extension, testBalloonProperties).flatMap { (key, value) ->
                        listOf("-P", "plugin:${Constants.COMPILER_PLUGIN_NAME}:$key=$value")
                    }
                }
            )
        }
    }
}

/**
 * Extension accessor (outside this project, it is generated by Gradle).
 */
fun Project.testBalloon(action: TestBalloonGradleExtension.() -> Unit) {
    extensions.configure<TestBalloonGradleExtension>(Constants.GRADLE_EXTENSION_NAME) {
        action()
    }
}
