@file:OptIn(TestBalloonInternalApi::class)
@file:Suppress("NewApi")

package de.infix.testBalloon.gradlePlugin.shared

import de.infix.testBalloon.framework.internal.EnvironmentVariable
import de.infix.testBalloon.framework.internal.PATH_PATTERN_SEPARATOR
import de.infix.testBalloon.framework.internal.TestBalloonInternalApi
import de.infix.testBalloon.framework.internal.TestReportingMode
import org.gradle.api.Project
import org.gradle.api.internal.tasks.testing.filter.DefaultTestFilter
import org.gradle.api.tasks.testing.AbstractTestTask
import org.gradle.api.tasks.testing.Test
import org.jetbrains.kotlin.gradle.dsl.KotlinBaseExtension
import org.jetbrains.kotlin.gradle.targets.js.testing.KotlinJsTest
import org.jetbrains.kotlin.gradle.targets.js.testing.karma.KotlinKarma
import org.jetbrains.kotlin.gradle.targets.native.tasks.KotlinNativeTest
import org.jetbrains.kotlin.gradle.testing.internal.KotlinTestReport
import java.nio.file.DirectoryNotEmptyException
import kotlin.io.path.Path
import kotlin.io.path.deleteIfExists
import kotlin.io.path.div
import kotlin.io.path.exists
import kotlin.io.path.writeText

internal fun Project.configureWithTestBalloon(testBalloonProperties: TestBalloonGradleProperties) {
    val generateTestBalloonInitializationTask = tasks.register("generateTestBalloonInitialization") {
        val generatedCommonTestDir = layout.buildDirectory.dir("generated/testBalloon/src/commonTest")
        outputs.dir(generatedCommonTestDir)
        doLast {
            val directory = Path("${generatedCommonTestDir.get()}/kotlin")
            check(directory.exists() || directory.toFile().mkdirs()) { "Could not create directory '$directory'" }
            (directory / "EntryPointAnchor.kt").writeText(
                """
                        package de.infix.testBalloon.framework.internal.entryPoint

                        // This file was generated by the TestBalloon Gradle plugin.
                        // The compiler plugin will populate it with entry point code. 

                """.trimIndent()
            )
        }
    }

    afterEvaluate {
        // Why use afterEvaluate at this point?
        // In order to reliably detect all top-level source sets, we must be sure that the source set hierarchy
        // has been completely set up. Otherwise, `dependsOn.isEmpty()` would detect false positives.
        extensions.configure<KotlinBaseExtension>("kotlin") {
            val testRootSourceSetRegex = testBalloonProperties.testRootSourceSetRegex
            sourceSets.configureEach {
                if (testRootSourceSetRegex.containsMatchIn(name) && dependsOn.isEmpty()) {
                    kotlin.srcDir(generateTestBalloonInitializationTask)
                }
            }
        }
    }

    val reportingMode = when (testBalloonProperties.reportingMode) {
        "intellij" -> TestReportingMode.INTELLIJ_IDEA
        "files" -> TestReportingMode.FILES
        else -> if (providers.systemProperty("idea.active").isPresent) {
            TestReportingMode.INTELLIJ_IDEA
        } else {
            TestReportingMode.FILES
        }
    }

    val reportsEnabled = testBalloonProperties.reportsEnabled ?: (reportingMode == TestReportingMode.FILES)

    if (!reportsEnabled) {
        tasks.withType(AbstractTestTask::class.java).configureEach {
            reports.html.required.set(false)
            reports.junitXml.required.set(false)
        }
        tasks.withType(KotlinTestReport::class.java).configureEach {
            enabled = false
        }
    }

    tasks.withType(Test::class.java) {
        // https://docs.gradle.org/current/userguide/java_testing.html
        useJUnitPlatform()

        // Ask Gradle to skip scanning for test classes. We don't need it as our compiler plugin already
        // knows. Does this make a difference? I don't know.
        isScanForTestClasses = false
    }

    afterEvaluate {
        tasks.withType(AbstractTestTask::class.java).configureEach {
            fun KotlinJsTest.configureKarmaEnvironment() {
                val directory = Path("${layout.projectDirectory}") / "karma.config.d"
                val parameterConfigFile = directory / "testBalloonParameters.js"

                /** Returns the prioritized patterns as a JS source string. */
                fun prioritizedPatterns(vararg primary: EnvironmentVariable, secondary: Iterable<String>): String {
                    val patterns = primary.firstNotNullOfOrNull {
                        providers.environmentVariable(it.name).orNull?.ifEmpty { null }
                            ?.split("${PATH_PATTERN_SEPARATOR}")
                    } ?: secondary

                    return patterns.joinToString("${PATH_PATTERN_SEPARATOR}", prefix = "\"", postfix = "\"") {
                        it.replace("\"", "\\\"")
                    }
                }

                val includePatternsJs = prioritizedPatterns(
                    EnvironmentVariable.TESTBALLOON_INCLUDE,
                    EnvironmentVariable.TEST_INCLUDE,
                    secondary = filter.includePatterns +
                        (filter as DefaultTestFilter).commandLineIncludePatterns
                )
                val excludePatternsJs = prioritizedPatterns(
                    EnvironmentVariable.TESTBALLOON_EXCLUDE,
                    secondary = filter.excludePatterns
                )

                doFirst {
                    @Suppress("NewApi")
                    check(directory.exists() || directory.toFile().mkdirs()) {
                        "Could not create directory '$directory'"
                    }

                    parameterConfigFile.writeText(
                        """
                                config.client = config.client || {};
                                config.client.env = {
                                    ${EnvironmentVariable.TESTBALLOON_INCLUDE.name}: $includePatternsJs,
                                    ${EnvironmentVariable.TESTBALLOON_EXCLUDE.name}: $excludePatternsJs,
                                    ${EnvironmentVariable.TESTBALLOON_REPORTING.name}: "$reportingMode"
                                }
                        """.trimIndent()
                    )
                }

                doLast {
                    @Suppress("NewApi")
                    if (parameterConfigFile.deleteIfExists()) {
                        try {
                            directory.deleteIfExists()
                        } catch (_: DirectoryNotEmptyException) {
                        }
                    }
                }
            }

            fun configureEnvironment(setTestEnvironment: (variable: EnvironmentVariable, value: String) -> Unit) {
                fun prioritizedPatterns(vararg primary: EnvironmentVariable, secondary: Iterable<String>): String =
                    primary.firstNotNullOfOrNull {
                        providers.environmentVariable(it.name).orNull?.ifEmpty { null }
                    }
                        ?: secondary.joinToString("${PATH_PATTERN_SEPARATOR}")

                setTestEnvironment(
                    EnvironmentVariable.TESTBALLOON_INCLUDE,
                    prioritizedPatterns(
                        EnvironmentVariable.TESTBALLOON_INCLUDE,
                        EnvironmentVariable.TEST_INCLUDE,
                        secondary = filter.includePatterns +
                            (filter as DefaultTestFilter).commandLineIncludePatterns
                    )
                )
                setTestEnvironment(
                    EnvironmentVariable.TESTBALLOON_EXCLUDE,
                    prioritizedPatterns(EnvironmentVariable.TESTBALLOON_EXCLUDE, secondary = filter.excludePatterns)
                )
                setTestEnvironment(EnvironmentVariable.TESTBALLOON_REPORTING, reportingMode.name)
            }

            when (this) {
                is KotlinNativeTest -> {
                    configureEnvironment { variable, value ->
                        environment(variable.name, value, false)
                    }
                }

                is KotlinJsTest -> {
                    if (testFramework is KotlinKarma) {
                        configureKarmaEnvironment()
                    } else {
                        configureEnvironment { variable, value ->
                            environment(variable.name, value)
                        }
                    }
                }

                is Test -> {
                    configureEnvironment { variable, value ->
                        environment(variable.name, value)
                    }
                }
            }
        }
    }
}
