package de.infix.testBalloon.gradlePlugin.layer.kotlin220

import com.android.build.api.variant.AndroidComponentsExtension
import com.android.build.api.variant.HasAndroidTest
import com.android.build.api.variant.HasUnitTest
import de.infix.testBalloon.framework.shared.internal.Constants
import de.infix.testBalloon.gradlePlugin.TestBalloonGradlePluginBase
import de.infix.testBalloon.gradlePlugin.testBalloonEnvironment
import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.FileCollection
import org.gradle.api.internal.tasks.testing.filter.DefaultTestFilter
import org.gradle.api.provider.Provider
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension
import org.jetbrains.kotlin.gradle.targets.js.testing.KotlinJsTest
import java.nio.file.DirectoryNotEmptyException
import kotlin.io.path.Path
import kotlin.io.path.deleteIfExists
import kotlin.io.path.div
import kotlin.io.path.exists
import kotlin.io.path.writeText

@Suppress("unused", "ClassName")
open class TestBalloonGradlePlugin_2_2_0 : TestBalloonGradlePluginBase() {
    override fun Project.addEntryPointSourceFileIfNecessary() {
        val generateTestBalloonEntryPointTask = tasks.register(
            "generateTestBalloonEntryPoint",
            GenerateTestBalloonEntryPointTask::class.java
        ) {
            generatedOutputDirectory.set(layout.buildDirectory.dir("generated/testBalloon/src"))
        }

        // AGP may effectively disable source directories added via Gradle's `srcDir`.
        // We use the variant API in order to avoid this. See https://github.com/infix-de/testBalloon/issues/84.
        try {
            extensions.findByType(AndroidComponentsExtension::class.java)
        } catch (_: NoClassDefFoundError) {
            null // The Android Gradle plugin providing the AndroidComponentsExtension is not on the classpath.
        }?.apply {
            onVariants { variant ->
                for ((componentName, sources) in mapOf(
                    "unitTest" to (variant as? HasUnitTest)?.unitTest?.sources,
                    "androidTest" to (variant as? HasAndroidTest)?.androidTest?.sources
                )) {
                    if (sources != null) {
                        debugLog(
                            "Adding test entry point to Android variant '${variant.name}', component '$componentName'"
                        )
                        sources.kotlin?.addGeneratedSourceDirectory(
                            generateTestBalloonEntryPointTask,
                            GenerateTestBalloonEntryPointTask::generatedOutputDirectory
                        )
                    }
                }
            }
        }

        extensions.configure<KotlinProjectExtension>("kotlin") {
            val testRootSourceSetRegex = testBalloonProperties.testRootSourceSetRegex
            val emptyFileCollection: FileCollection = layout.files()

            sourceSets.configureEach {
                val sourceSet = this
                kotlin.srcDir(
                    provider {
                        if (testRootSourceSetRegex.containsMatchIn(sourceSet.name) && sourceSet.dependsOn.isEmpty() ||
                            testBalloonProperties.isJvmTestSuite(sourceSet.name)
                        ) {
                            debugLog("Adding test entry point to Kotlin source set '${sourceSet.name}'")
                            generateTestBalloonEntryPointTask
                        } else {
                            debugLog("No test entry point required for Kotlin source set '${sourceSet.name}'")
                            emptyFileCollection // null should be acceptable, but apparently isn't.
                        }
                    }
                )
            }
        }
    }

    @CacheableTask
    abstract class GenerateTestBalloonEntryPointTask : DefaultTask() {
        @get:OutputDirectory
        abstract val generatedOutputDirectory: DirectoryProperty

        @Suppress("NewApi")
        @TaskAction
        fun generate() {
            val directory = generatedOutputDirectory.get().asFile
            if (directory.exists()) directory.deleteRecursively()
            check(directory.mkdirs()) { "Could not create directory '$directory'" }
            val jvmEntryPointClassSimpleName = Constants.JVM_ENTRY_POINT_CLASS_NAME.substringAfterLast('.')
            (directory.toPath() / "$jvmEntryPointClassSimpleName.kt").writeText(
                """
                    package ${Constants.ENTRY_POINT_PACKAGE_NAME}

                    // This file was generated by the TestBalloon Gradle plugin.
                    // The compiler plugin will populate it with entry point code.

                    internal class $jvmEntryPointClassSimpleName { // for JVM targets
                        companion object {
                            internal fun ${Constants.JVM_DISCOVERY_RESULT_METHOD_NAME}() {}
                        }
                    }
                    
                    public suspend fun main() {} // for JS and Wasm targets
                    
                    private val testFrameworkNativeEntryPoint: Unit = Unit

                """.trimIndent()
            )
        }
    }

    override fun KotlinJsTest.configureKarma(project: Project) {
        if (!browserAutoIntegrationEnabled()) return

        val directory = Path("${project.layout.projectDirectory}") / "karma.config.d"
        val parameterConfigFile = directory / "testBalloonParameters.js"

        val secondaryIncludePatterns = (
            filter.includePatterns + (filter as DefaultTestFilter).commandLineIncludePatterns
            ).toList()
        val secondaryExcludePatterns = filter.excludePatterns.toList()

        val browserSafeEnvironmentPattern: Provider<String> = project.provider {
            extension.browserSafeEnvironmentPattern
                ?: testBalloonProperties.browserSafeEnvironmentPattern
        }

        val testBalloonEnvironment = project.testBalloonEnvironment(
            secondaryIncludePatterns,
            secondaryExcludePatterns
        )

        doFirst {
            @Suppress("NewApi")
            check(directory.exists() || directory.toFile().mkdirs()) {
                "Could not create directory '$directory'"
            }

            // The environment propagated to the browser. TestBalloon's own entries have precedence.
            val browserSafeEnvironmentPattern = browserSafeEnvironmentPattern.get().ifEmpty {
                null
            }?.toRegex()
            val browserEnvironment =
                System.getenv().filter { (name, _) ->
                    browserSafeEnvironmentPattern?.containsMatchIn(name) == true
                } + testBalloonEnvironment

            val clientConfiguration = buildList {
                add("config.client = config.client || {};")
                add("config.client.env = {")

                add(
                    browserEnvironment.map { (name, value) ->
                        val escapedValue = value
                            .replace("\\", "\\\\")
                            .replace("\"", "\\\"")
                            .filter { it.code >= 0x20 }
                        """    $name: "$escapedValue""""
                    }.joinToString(separator = ",\n")
                )

                add("}")
            }

            parameterConfigFile.writeText(clientConfiguration.joinToString(separator = "\n"))
        }

        doLast {
            @Suppress("NewApi")
            if (parameterConfigFile.deleteIfExists()) {
                try {
                    directory.deleteIfExists()
                } catch (_: DirectoryNotEmptyException) {
                }
            }
        }
    }
}
