== TestBalloon Examples

=== Using the Core Library

The link:../examples/general[examples/general] directory is intended to provide source code samples for all TestBalloon features in link:../examples/general/src/commonTest[commonTest].

To run them all:

* `gradlew --quiet :examples:core:cleanAllTests :examples:core:allTests`

As usual, you can run examples for a single target:

* `gradlew --quiet :examples:general:cleanAllTests :examples:general:jvmTest`
* `gradlew --quiet :examples:general:cleanAllTests :examples:general:jsNodeTest`
* `gradlew --quiet :examples:general:cleanAllTests :examples:general:jsBrowserTest`
* `gradlew --quiet :examples:general:cleanAllTests :examples:general:wasmJsNodeTest`
* `gradlew --quiet :examples:general:cleanAllTests :examples:general:wasmJsBrowserTest`
* `gradlew --quiet :examples:general:cleanAllTests :examples:general:wasmWasiNodeTest`
* `gradlew --quiet :examples:general:cleanAllTests :examples:general:linuxX64Test`


=== Using Integrations

==== Kotest Assertions

Some features of the Kotest Assertions library require extra setup, e.g. soft assertions. The link:../testBalloon-integration-kotest-assertions[testBalloon-integration-kotest-assertions] directory demonstrates how to use those with TestBalloon.
