#!/bin/bash

. "$(dirname "$0")/.setup"

for script in release-scripts/*; do
  case "$script" in
    release-scripts/.*) ;;
    release-scripts/00*) ;;
    *) REPEAT_PACKAGE_LOCK_FILES_UPDATE=yes "$script"
  esac
done
