#!/bin/bash

trap 'status=$?; echo -e "\n*** $(basename "$0") completed with status $status ***\n"' EXIT
set -e

cd "$(dirname "$0")/.." || exit 2

for script in release-scripts/*; do
  case "$script" in
    release-scripts/00*) ;;
    *) REPEAT_PACKAGE_LOCK_FILES_UPDATE=yes "$script"
  esac
done
