#!/bin/bash

. "$(dirname "$0")/.setup"

find . -type d -name kotlin-js-store -print | sort |
while read -r js_store_directory; do
  rm -f "$js_store_directory/package-lock.json"
  rm -f "$js_store_directory/wasm/package-lock.json"
done
