#!/bin/bash

. "$(dirname "$0")/.setup"

function upgradePackageLockFiles() {
  ./gradlew --warn --continue kotlinUpgradePackageLock kotlinWasmUpgradePackageLock :testBalloon-framework-shared:kotlinUpgradePackageLock :testBalloon-framework-shared:kotlinWasmUpgradePackageLock
}

upgradePackageLockFiles || {
  log "second try"
  upgradePackageLockFiles
}

if [ "${REPEAT_PACKAGE_LOCK_FILES_UPDATE:-no}" == "yes" ]; then
  log "repeating"
  upgradePackageLockFiles
fi
