#!/bin/bash

trap 'status=$?; echo -e "\n*** $(basename "$0") completed with status $status ***\n"' EXIT
set -e

cd "$(dirname "$0")/.." || exit 2

./gradlew --warn kotlinUpgradePackageLock kotlinWasmUpgradePackageLock

if [ "${REPEAT_PACKAGE_LOCK_FILES_UPDATE:-no}" == "yes" ]; then
  ./gradlew --warn kotlinUpgradePackageLock kotlinWasmUpgradePackageLock
fi
