#!/bin/bash

. "$(dirname "$0")/.setup"

function upgradePackageLockFiles() {
  PACKAGE_LOCK_FILES_UPDATE_REQUESTED=true ./gradlew --warn :integration-test:test
}

upgradePackageLockFiles || {
  log "second try"
  upgradePackageLockFiles
}

if [ "${REPEAT_PACKAGE_LOCK_FILES_UPDATE:-no}" == "yes" ]; then
  log "repeating"
  upgradePackageLockFiles
fi
