#!/bin/bash

. "$(dirname "$0")/.setup"

./gradlew --warn checkLegacyAbi
./gradlew --warn lintKotlin

log "starting componentTestsAllTargets"

./gradlew componentTestsAllTargets

log "starting integrationTests"

./gradlew integrationTests
