#!/bin/bash

trap 'status=$?; echo -e "\n*** $(basename "$0") completed with status $status ***\n"' EXIT
set -e

cd "$(dirname "$0")/.." || exit 2

./gradlew --warn checkLegacyAbi
./gradlew --warn lintKotlin
./gradlew componentTestsAllTargets
./gradlew integrationTests
