#!/bin/bash

. "$(dirname "$0")/.setup"

./gradlew --warn checkLegacyAbi
./gradlew --warn lintKotlin

log "starting componentChecks"

./gradlew componentChecks --no-configuration-cache --continue

log "stopping Gradle daemons"

./gradlew --stop

log "starting integrationTests"

./gradlew -Dorg.gradle.jvmargs="-Xmx512m -XX:MaxMetaspaceSize=384m" integrationTests
