:icons: font

== Android Platform Support

=== Status

Starting with 0.6.0 releases, TestBalloon fully supports Android host-side tests (a.k.a. unit tests) and Android device-side tests (a.k.a. instrumented tests). Releases 0.7.0 and above support using JUnit 4 rules in TestBalloon tests.

All TestBalloon capabilities work on Android, except concurrent/parallel test invocation (which apparently conflicts with the Android test infrastructure's handling of Activities). Nested test suites are supported.

Existing tests based on JUnit 4 continue to function and run alongside TestBalloon tests.

=== Android Test Ecosystem

==== Test types

Android uses https://developer.android.com/training/testing/fundamentals[two types of tests]:

1. *Host-side tests*: These execute on the development machine or a server.
** Default source folder: `src/test`
** Default dependency notation: `testImplementation(…)`
** Default test module names: `++${baseModule}_debugUnitTest++`, `++${baseModule}_releaseUnitTest++`
** Default compilations: `debugUnitTest`, `releaseUnitTest`
2. *Device-side tests*: These run on an Android device, either physical or emulated. (Some unit tests fall into this category.)
** Default source folder: `src/androidTest`
** Default dependency notation: `androidTestImplementation(...)`
** Default test module names: `++${baseModule}_debugAndroidTest++`
** Default compilations: `debugAndroidTest`

==== Test frameworks

Android uses *JUnit 4* as its test framework.

NOTE: Support for JUnit 5 https://issuetracker.google.com/issues/127100532[has long been requested], but https://issuetracker.google.com/issues/127100532#comment42[rejected as of Oct 24, 2024].

NOTE: In April 2025, work on https://issuetracker.google.com/issues/127100532#comment55[Gradle test suite support] has been reported, but, contrary to initial interpretations, this does not imply any integration of alternative test frameworks.

==== Test support libraries

* *https://developer.android.com/training/testing/local-tests/robolectric[Robolectric]*: A simulated Android environment that runs inside a JVM. Faster and less flaky than using an emulator, but does not support all features and APIs.
* *Espresso*: A library for Android view tests.
