:icons: font

== TestBalloon Development

This document explains what TestBalloon is composed of, how its parts interact, and tasks used in TestBalloon development.

=== Components

TestBalloon comprises these components (appearing as Gradle subprojects):

. *testBalloon-framework-core*: The Kotlin Multiplatform library containing all core framework functions.
. *testBalloon-compiler-plugin*: A Kotlin compiler plugin generating code to discover all top-level test suites and run them as directed by Kotlin's standard Gradle test tasks. Think of it as providing the `main()` function for tests.
. *testBalloon-gradle-plugin*: A Gradle plugin enabling the TestBalloon Kotlin compiler plugin, and providing a `testBalloon` extension for configuration.
. *testBalloon-framework-shared*: Types and constants shared between the core library, the compiler plugin, and the IDE plugin.

In addition to the above, there are *testBalloon-integration-** modules, providing TestBalloon interoperability with other test-related libraries.

=== Concepts

==== Basic Elements

TestBallon differentiates between a `Test` and a `TestSuite`, commonly referred to as test elements.

* A `Test` is the unit of test execution, which can either succeed or fail.
* A `TestSuite` is a container for lower-level ``Test``s and/or ``TestSuite``s.

Since ``TestSuite``s nest, they can build a tree of test elements.

==== Core Classes

TestBalloon' core classes are:

* `TestElement`
** `Test`
** `TestSuite`
*** `TestSession` – to orchestrate everything, one per compilation module
*** `TestCompartment` – to isolate tests with different concurrency and runtime requirements

==== Test Element Tree

The core classes form the test element tree with

* a `TestSession` at the top,
* ``TestCompartment``s below, then
* ``TestSuite``s, and finally
* ``Test``s at the leaves.

Since each of them is a `TestElement`, they have much in common.

==== Configuration

TestBalloon has a single point of configuration: The `TestElement`.

Each `TestElement` has a `testConfig` parameter, which is used to configure everything from global configuration (`TestSession`) down to individual ``Test``s via one universal mechanism.

=== Interactions

==== Compile Time

TestBalloon's compiler plugin

* discovers top-level test suites via their signature (lazily initialized delegated properties of type `TestSuite`),
* injects fully qualified names into top-level `testSuite` invocations, uniquely identifying their location,
* discovers a possible `TestSession` class,
* creates (IR) code to initialize and start the framework.

==== Run Time

Plugin-generated code

* calls `initializeTestFramework`, which sets up the `TestSession`,
+
--
NOTE: The `TestSession` must exist before top-level test suites are initialized.
--
* initializes all top-level test suites,
+
--
NOTE: Top-level test suites wire themselves to the second level of the test element tree, their ``TestCompartment``s, which connect to the `TestSession` at the top.
--
* calls `configureAndExecuteTests`, which does what its name implies.

A test run comprises two phases:

1. `TestSession.global.parameterize` configures its entire test element tree, which includes
* creating lower-level test elements,
* parameterizing test elements (e.g. selecting element subsets or disabling elements).
2. `TestSession.global.execute` executes tests (entirely or selected subsets).

=== Tasks

==== Local Publishing

You can publish a TestBallon version locally by

1. setting a version number in `gradle.properties`,
2. running `gradlew publishToMavenLocal`.

Alternatively, you can publish locally to `$HOME/.m2/local-repository` by

* running `gradlew publishAllPublicationsToLocalRepository`

==== Testing

TestBallon has a three-stage test process, built into the IDE run configuration `ciTests`:

1. `gradlew checkLegacyAbi`
2. `gradlew componentTestsAllTargets`
3. `gradlew integrationTests`

==== Debugging the Compiler Plugin

1. Run the compiler plugin in-process with Gradle.
+
--
To run the Gradle tasks `clean compileTestKotlinJvm` for the link:../examples/general[examples/general] project:

* `gradlew -Dorg.gradle.debug=true -Pkotlin.compiler.execution.strategy=in-process :examples:general:clean :examples:general:compileTestKotlinJvm`
--

2. Attach the JVM debugger to port 5005. In IntelliJ IDEA, use the command _Run – Attach to Process_.

==== Other

A separate document explains xref:Release_Process.adoc[TestBalloon's release process].
