:icons: font

=== Release Process

==== Choose Kotlin versions

Each TestBallon version should produce releases for the most recent stable Kotlin versions, plus the most recent EAP version. Those versions are listed at https://kotlinlang.org/docs/home.html[Kotlin Docs] under https://kotlinlang.org/docs/whatsnew-eap.html[_What's new in Kotlin_] and _Kotlin evolution and roadmap_ – https://kotlinlang.org/docs/releases.html[_Kotlin releases_].

==== Update documentation

. Update the version in xref:../gradle.properties[gradle.properties].
. Update documentation contents.
. Update the xref:../CHANGELOG.md[CHANGELOG], including the new version number.
. Update the documentation website: `gradlew documentationWebsiteUpdate -Plocal.documentation.useProjectVersion=true`
. Serve the website locally: `gradlew documentationWebsiteServiceStart`
. Verify the API reference contents.
. Verify documentation contents.
. Migrate the documentation to the actual version: `gradlew documentationWebsiteMigrateVersion`
. Update the documentation website (next `dev` version): `gradlew documentationWebsiteUpdate`

==== Prepare a release branch for a Kotlin version

. For each Kotlin version, choose a branch under `releases`, like `releases/0.4.0-K2.2.0`, where `0.4.0` is the TestBalloon version and `2.2.0` is the Kotlin version.
. Prepare the release branch from `main` or a previous release branch.
. Check out the release branch.
. Change the version in `gradle.properties`, like `version=0.4.0-K2.2.0-dev1`.
. Adapt versions in `gradle/libs.versions.toml`.
. Make necessary source code changes.
. Update package lock files:
.. Run `./gradlew clean`
.. Delete lock files
*** `kotlin-js-store/package-lock.json`
*** `kotlin-js-store/wasm/package-lock.json`
.. Recreate lock files:
+
[source,bash]
----
./gradlew kotlinUpgradePackageLock kotlinWasmUpgradePackageLock
----
. Run `./gradlew updateLegacyAbi`
. Run CI tests via the IntelliJ IDEA run configuration `ciTests`.
. Check in the integration test project that no newer Kotlin artifacts sneak in, using a Terminal:
** `++(cd integration-test/build/projects/element-selection; ./gradlew dependencies) | awk '/kotlin-stdlib:/ { gsub(/.*kotlin-stdlib:/, ""); gsub(/.* -> /, ""); gsub(/ \(.\)$/, ""); print }' | sort -u++`
. Commit changes
. Push commits to GitHub.

==== Publish a release to MavenCentral

NOTE: Publish releases in the order they should appear on MavenCentral (and release badges):
Pre-release first, then regular releases in increasing version number order.

. Wait for CI validation.
. Wait for previous MavenCentral publications to finish.
. Tag the release commit like `0.4.0-K2.2.0`.
. Push the tag to GitHub – this will trigger the publication to MavenCentral.

==== Publish a release on GitHub

. Wait for the MavenCentral publication to finish.
. https://github.com/infix-de/testBalloon/releases/new[Create a new release], selecting
** The current release tag, and
** The previous release tag for comparison.
. Generate release notes.
. Adapt release notes, extracting them from the xref:../CHANGELOG.md[CHANGELOG].
. Adapt the comparison link as necessary.
. Check or clear _Set as a pre-release_ and _Set as the latest release_.
. Click _publish_.
