:icons: font

=== Release Process

==== Choose Kotlin versions

Each TestBallon version should produce releases for the most recent stable Kotlin versions, plus the most recent EAP version. Those versions are listed at https://kotlinlang.org/docs/home.html[Kotlin Docs] under https://kotlinlang.org/docs/whatsnew-eap.html[_What's new in Kotlin_] and _Kotlin evolution and roadmap_ – https://kotlinlang.org/docs/releases.html[_Kotlin releases_].

==== Update documentation

. Update the version in xref:../gradle.properties[gradle.properties].
. Update documentation contents.
. Update the xref:../CHANGELOG.md[CHANGELOG], including the new version number.
. Update the documentation website: `gradlew documentationWebsiteUpdate -Plocal.documentation.useProjectVersion=true`
. Serve the website locally: `gradlew documentationWebsiteServiceStart`
. Verify the API reference contents.
. Verify documentation contents.
. Migrate the documentation to the actual version: `gradlew documentationWebsiteMigrateVersion`
. Update the documentation website (next `dev` version): `gradlew documentationWebsiteUpdate`

==== Prepare a release branch for a Kotlin version

. For each minor version, choose a branch under `releases`, like `releases/1.1`.
. Prepare the release branch from `main` or a previous release branch.
. Check out the release branch.
. Change the version in `gradle.properties`, like `version=1.1.0-dev-1`.
. Adapt versions in `gradle/libs.versions.toml`.
. Make necessary source code changes.
. Run `./prepare-release`
. Run `./gradlew check -x test --continue` and verify that everything compiles and runs, accepting failed tests (from examples and experiments).
. Commit changes
. Push commits to GitHub.

==== Publish a release to MavenCentral

. Wait for CI validation.
. Add a release tag like `1.1.0` via the IDE (or run `git tag 1.1.0 releases/1.1`).
. Push the release tag via the IDE (or run `git push origin tag 1.1.0`.

==== Publish a release on GitHub

. Wait for the final MavenCentral publication to finish.
. https://github.com/infix-de/testBalloon/tags[Choose its tag]
. Select _ Create release from tag_
. Choose the corresponding _Previous tag_.
. Select _Generate release notes_.
. Adapt release notes, extracting them from the xref:../CHANGELOG.md[CHANGELOG].
. Adapt the comparison link as necessary.
. Check or clear _Set as a pre-release_ and _Set as the latest release_.
. Click _publish_.
