:icons: font

=== Release Process

==== Choose Kotlin versions

Each TestBallon version should produce releases for the most recent stable Kotlin versions, plus the most recent EAP version. Those versions are listed at https://kotlinlang.org/docs/home.html[Kotlin Docs] under _What's new in Kotlin_.

==== Update documentation

. Update the API reference: `gradlew dokkaGenerateHtml`
. Serve the website locally: `gradlew docSiteServe`
. Verify the API reference contents.
. Verify documentation contents.
. Prepare release documentation (breaking changes, what's new, what's fixed, other).

==== Prepare a release branch for a Kotlin version

. For each Kotlin version, choose a branch under `releases`, like `releases/0.4.0-K2.2.0`, where `0.4.0` is the TestBalloon version and `2.2.0` is the Kotlin version.
. Prepare the release branch from `main` or a previous release branch.
. Check out the release branch.
. Change the version in `gradle.properties`, like `version=0.4.0-K2.2.0-SNAPSHOT`.
. Adapt versions in `gradle/libs.versions.toml`.
. Make necessary source code changes.
. Update package lock files:
.. Run `./gradlew clean`
.. Delete lock files
*** `kotlin-js-store/package-lock.json`
*** `kotlin-js-store/wasm/package-lock.json`
.. Recreate lock files:
+
[source,bash]
----
./gradlew kotlinUpgradePackageLock kotlinWasmUpgradePackageLock
----
. Run `./gradlew updateLegacyAbi`
. Run CI tests via the IntelliJ IDEA run configuration `ciTests`.
. Check in the integration test project that no newer Kotlin artifacts sneak in, using a Terminal:
** `++(cd integration-test/build/projects/element-selection; ./gradlew dependencies) | awk '/kotlin-stdlib:/ { gsub(/.*kotlin-stdlib:/, ""); gsub(/.* -> /, ""); gsub(/ \(.\)$/, ""); print }' | sort -u++`
. Commit changes
. Tag the release commit like `0.4.0-K2.2.0`.
. Push commits to GitHub.

==== Prepare a release on GitHub

. Wait for CI validation.
. https://github.com/infix-de/testBalloon/releases/new[Create a new release], selecting
** The current release tag, and
** The previous release tag for comparison.
. Generate release notes.
. Adapt release notes.
. Adapt the comparison link as necessary.
. Check or clear _Set as a pre-release_ and _Set as the latest release_.
. Save draft.

==== Publish a release to MavenCentral

NOTE: Publish releases in the order they should appear on MavenCentral (and release badges):
Pre-release first, then regular releases in increasing version number order.

. Wait for previous publications to finish.
. Publish the release.
