plugins {
    id("buildLogic.multiplatform-plus-android-library")
    id("buildLogic.publishing-multiplatform")
}

description = "Core library for the TestBalloon framework"

kotlin {
    js {
        // The core library tests use kotlin-test, which comes with a default timeout of 2 seconds on JS.
        // This may be too restrictive on slow CI runners, so we are increasing it.
        val kotlinTestTimeout = "10s"
        nodejs { testTask { useMocha { timeout = kotlinTestTimeout } } }
        browser { testTask { useMocha { timeout = kotlinTestTimeout } } }
    }

    androidLibrary {
        namespace = "de.infix.testBalloon.framework.core"
    }

    sourceSets {
        commonMain {
            dependencies {
                api(projects.testBalloonFrameworkAbstractions)
                // kotlin-test provides the startUnitTests() function required by Kotlin/Wasm. This could also
                // be generated by the compiler plugin, but doing so would prevent library consumers from using
                // kotlin-test for assertions due to a then-redefined symbol for startUnitTests().
                implementation(kotlin("test"))
                api(libs.org.jetbrains.kotlinx.coroutines.core)
                api(libs.org.jetbrains.kotlinx.coroutines.test)
                implementation(libs.org.jetbrains.kotlinx.kotlinx.datetime)
                implementation(libs.org.jetbrains.kotlinx.atomicfu)
            }
        }

        jvmMain {
            dependencies {
                implementation(libs.org.junit.platform.engine)
            }
        }

        androidMain {
            dependencies {
                implementation(libs.androidx.test.core)
                implementation(libs.junit.junit4)
            }
        }

        jvmTest {
            dependencies {
                implementation(libs.org.jetbrains.kotlinx.coroutines.swing)
            }
        }
    }
}

tasks.withType<Test>().configureEach {
    // https://docs.gradle.org/current/userguide/java_testing.html
    useJUnitPlatform {
        excludeEngines("de.infix.testBalloon")
    }
}
