name: 'Publish the documentation website artifact'
on: [ workflow_call ]
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: publish-website
  cancel-in-progress: false

jobs:
  publish:
    if: github.event.repository.fork == false

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 'Deploy artifact to GitHub Pages'
        id: deployment
        # https://github.com/actions/deploy-pages/releases
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
